### ISSUE TITLE
Using your model with high resolution images 

### ISSUE THREAD

**Issue by Scienceseb** [sangmin-git/LMC-Memory#10]
Hello, 
I would like to have your opinion on the modifications I should make to your code so that it can be used for video prediction with large images, about 512x1024. 

Thanks for your help and of course I will cite your work in mine.

Kind regards,
Sébastien de Blois

**Comment by sangmin-git** [comment]
I think it depends on the characteristics of the dataset. If the motions involve lots of global interactions in a high-resolution video (e.g., interaction between the upper left part and lower right part in a video), deeper encoder/decoder and larger channel/memory sizes are needed to guarantee sufficient receptive field and motion capacity. Otherwise, the current model still can work.

P.S. Since the current code is written for square frames, you need to divide `img_size` into two variables (width and height) and to modify relevant parts (e.g., metric function in utils.py). 

Thanks!

**Comment by Scienceseb** [comment]
The dataset is a mining flottation dataset so there is a lot of motions but not complicated one, it is a flow, like a semi-fluid. Here is an exemple of two successive frames. 
![3342 64](https://user-images.githubusercontent.com/26779418/138740750-e5ba7998-e821-4cea-a793-4fbc3581121e.jpeg)
![3342 89](https://user-images.githubusercontent.com/26779418/138740888-287577f9-c3e0-4ac4-a71d-0028c466f39e.jpeg)

**Comment by Scienceseb** [comment]
So my modification is not working for a reason I dont understand : 
```
self.encoder = nn.Sequential(
            nn.Conv2d(in_channels=args.img_channel, out_channels=64, kernel_size=(3, 3), stride=2, padding=1),
            nn.ELU(),
            nn.Conv2d(in_channels=64, out_channels=128, kernel_size=(3, 3), stride=1, padding=1),
            nn.ELU(),
            nn.Conv2d(in_channels=128, out_channels=256, kernel_size=(3, 3), stride=2, padding=1),
            nn.ELU(),
            nn.Conv2d(in_channels=256, out_channels=256, kernel_size=(3, 3), stride=1, padding=1),
            nn.ELU())

self.decoder = nn.Sequential(
            nn.ConvTranspose2d(in_channels=512, out_channels=256, kernel_size=(3, 3), stride=1, padding=1, output_padding=0),
            nn.ELU(),
            nn.ConvTranspose2d(in_channels=256, out_channels=128, kernel_size=(3, 3), stride=2, padding=1, output_padding=1),
            nn.ELU(),
            nn.ConvTranspose2d(in_channels=128, out_channels=64, kernel_size=(3, 3), stride=1, padding=1, output_padding=0),
            nn.ELU(),
            nn.ConvTranspose2d(in_channels=64, out_channels=args.img_channel, kernel_size=(3, 3), stride=2, padding=1, output_padding=1))

self.convlstm_in_c = [256, 256, 256, 256]
self.convlstm_out_c = [256, 256, 256, 256]
```

I think the problem is at that point: 
```
self.attention_size = 128
self.attention_func = nn.Sequential(
    nn.AdaptiveAvgPool2d([1, 1]),
    nn.Flatten(),
    nn.Linear(256, 16),
    nn.ReLU(),
    nn.Linear(16, self.attention_size),
    nn.Sigmoid())
```

I also tried that variation (doubling the size) still not working:
```
self.attention_size = 256
self.attention_func = nn.Sequential(
    nn.AdaptiveAvgPool2d([1, 1]),
    nn.Flatten(),
    nn.Linear(512, 16),
    nn.ReLU(),
    nn.Linear(16, self.attention_size),
    nn.Sigmoid())
```

I got that error: `RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x384 and 256x16). `

**Comment by sangmin-git** [comment]
1. Sorry for the late reply, I think it is quite difficult to predict the long-term future with such dataset because it has irregular structures and movements. For example, shadow appears and disappears almost randomly even in two successive frames, which is very unpredictable. Thus, it is recommended to at least increase the capacity of the network considering the complexity of the dataset.

2. Since `memory_feature` has 128 channel size and convlstm output `c` has 256 channel size in your code,  `nn.Linear(256, 16)` should be changed to `nn.Linear(128+256, 16)`. Note that convlstm output `c` and `memory feature` are concatenated and then pass through fc layer.
